"""Database create

Revision ID: fb87e9403298
Revises: 60b805f94d91
Create Date: 2024-07-10 15:19:57.257358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb87e9403298'
down_revision: Union[str, None] = '60b805f94d91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('basket_id_key', 'basket', type_='unique')
    op.drop_constraint('category_id_key', 'category', type_='unique')
    op.drop_constraint('product_id_key', 'product', type_='unique')
    op.drop_constraint('user_id_key', 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_id_key', 'user', ['id'])
    op.create_unique_constraint('product_id_key', 'product', ['id'])
    op.create_unique_constraint('category_id_key', 'category', ['id'])
    op.create_unique_constraint('basket_id_key', 'basket', ['id'])
    # ### end Alembic commands ###
